# Generated by Django 4.2.18 on 2025-01-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'CustomerDetail',
                'verbose_name_plural': 'CustomerDetails',
            },
        ),
    ]
